slurm_header:
    project: microbial
    name: MIC3108
    qos: normal
    trim:
      type: core
      number: 2
      time: 02:20:00
    align:
        type: core
        number: 4
        time: 04:00:00
    process:
        type: core
        number: 1
        time: 01:00:00
    kraken:
        type: node
        number: 1
        time: 04:00:00

trim_config:
    quality: 20
    max_error_frac: 0.1
    min_length: 20

mapp_config:
    max_alignments: 20
    max_pair_mismatches: 999
    max_pair_mismatches_fraction: 0.04
    numThreads: 2

kraken_config:
    db_loc: mnt/hds/proj/cust053/tanja_analysis/kraken/databases/db_stndHuman_fin_build

folder_locations:
    genome_setup: /mnt/hds/proj/cust053/tanja_analysis/meta_EVD68/genomeDir
    #ref_fasta: /mnt/hds/proj/cust053/tanja_analysis/meta_EVD68/viralGenome/EVD68.fasta
    ref_fasta: /Users/tanjanormark/Documents/EVD68/EVD68.fasta
